[package]
name = "rustysandbox"
version = "0.1.0"
authors = ["alexanderheim <alexanderheimat@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.1"
rand = "0.7.3"
